### ISSUE TITLE
Possibly a typo in variance calculation

### ISSUE THREAD

**Issue by dmikushin** [tbrouns/eyestalker#4]
Dear Dr. Brouns,

Thank you for making the excellent EyeStalker software public.

Perhaps there is a typo in the line below: should it be `mEdgePropertiesNew` instead of `mEdgeProperties`? Could you please kindly confirm? Thanks!

https://github.com/tbrouns/eyestalker/blob/c35660149f1e2e3ad0d3ab6dc65218704e9482a9/source/eyestalker.cpp#L1854

**Comment by tbrouns** [comment]
Fixed
